### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by Star-KWL** [maotoumao/weread-dailyquestion-helper#1]
前三步做完了，没用过python，然后去官网装了一个3.6.8（已添加path)，但是打开main.py后会闪一下命令行窗口然后就消失了，请问是哪里出了问题

**Comment by maotoumao** [comment]
可以用控制台进入项目文件夹，然后执行
`python ./main.py`
看下错误信息~ 正常情况下应该是没问题的（前不久刚试过

**Comment by Star-KWL** [comment]
> 

Traceback (most recent call last):
  File "./main.py", line 5, in <module>
    from PIL import ImageChops
ModuleNotFoundError: No module named 'PIL'

**Comment by Star-KWL** [comment]
我陆续安装了pillow，pypiwin32，baidu_aip，chardet，bs4后终于有用了，建议还是完善一下教程😄

**Comment by maotoumao** [comment]
有些包没装 项目目录下控制台执行pip install -r requirements.txt，装完后再运行




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月02日 14:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [maotoumao/weread-dailyquestion-helper] 求教 (Issue #1) |

Traceback (most recent call last):
File "./main.py", line 5, in
from PIL import ImageChops
ModuleNotFoundError: No module named 'PIL'
