### ISSUE TITLE
怎么用的，图片看不了了

### ISSUE THREAD

**Issue by XiaoNing0430** [maotoumao/weread-dailyquestion-helper#3]
怎么用的，图片看不了了

**Comment by maotoumao** [comment]
把url上的github换成gitee试试～ 我记得我也推到了gitee上



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月10日 22:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maotoumao/weread-dailyquestion-helper] 怎么用的，图片看不了了 (Issue #3) |

怎么用的，图片看不了了
